// routes/timetableDownload.js
import express from "express";
import PDFDocument from "pdfkit";
import db from '../../middlewares/db.js';

const router = express.Router();

// Utility: Safe string
const safeString = (val) => (val === null || val === undefined ? "" : String(val).trim());

// Modern green theme
const theme = {
  primary: "#16a34a",
  secondary: "#065f46",
  text: "#111827",
  lightGray: "#f3f4f6",
};

// New time slots (make sure these match your DB column names)
const TIME_SLOTS = [
  "04:30-05:15",
  "05:15-06:00",
  "06:00-06:45",
  "06:45-07:30",
  "07:30-08:15",
  "08:15-09:00",
];

// ================== ROUTE ==================
router.get("/download/:teacherName", async (req, res) => {
  try {
    const teacherName = safeString(req.params.teacherName);
    if (!teacherName) return res.status(400).send("Teacher name required.");

    // Query timetable for this teacher
    const [rows] = await db.query(
      "SELECT * FROM teachers_timestable WHERE Teachers = ? ORDER BY Day",
      [teacherName]
    );

    if (!rows.length) return res.status(404).send("No timetable found for this teacher.");

    // Create PDF
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${teacherName}_timetable.pdf"`
    );
    doc.pipe(res);

    // Title
    doc
      .fontSize(22)
      .fillColor(theme.primary)
      .text("Teacher Timetable", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(16)
      .fillColor(theme.secondary)
      .text(teacherName, { align: "center" })
      .moveDown(1.5);

    // Table header
    const startX = doc.x;
    let y = doc.y;

    doc
      .fontSize(12)
      .fillColor(theme.text)
      .text("Day", startX, y, { width: 80, bold: true });

    TIME_SLOTS.forEach((slot, i) => {
      doc
        .fillColor(theme.text)
        .text(slot, startX + 90 + i * 75, y, { width: 75, align: "center" });
    });

    y += 20;
    doc.moveTo(startX, y).lineTo(550, y).strokeColor(theme.primary).stroke();
    y += 10;

    // Table rows
    rows.forEach((row) => {
      doc.fillColor(theme.secondary).fontSize(11).text(row.Day, startX, y, { width: 80 });

      TIME_SLOTS.forEach((slot, i) => {
        const val = safeString(row[slot]) || "—";
        doc
          .fillColor(val === "—" ? "#9ca3af" : theme.text)
          .text(val, startX + 90 + i * 75, y, {
            width: 75,
            align: "center",
          });
      });

      y += 20;
      if (y > 750) {
        doc.addPage();
        y = 50;
      }
    });

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text("Generated by Manfess Timetable System", { align: "center" });

    doc.end();
  } catch (err) {
    console.error("PDF generation error:", err);
    res.status(500).send("Failed to generate timetable PDF.");
  }
});

export default router;
